#!/bin/bash

if [ x"$1" == x"-d" ]; then
    set -x
    shift
fi


set_defaults() {
    : ${BUILD_CONFIG:=default}
    : ${REMOTE_NAME:=dummy-remote}
    : ${REMOTE_DIR:=ci-builds/$BUILD_CONFIG}
}

local_config() {
    # allow user to override default settings
    # normally settings should use
    #   : ${VAR:=value}
    # in which case the first one processed wins
    # ENV vars, project local, the project checked in, the global user
    # use of
    #   VAR=value
    # means an override, last one processed wins
    # global user, project checked in, project local, env vars
    for d in .prjinfo/local .prjinfo  ~/.prjinfo ; do
        if [ -r $d/setenv ]; then
            . $d/setenv
        fi
    done

    set_defaults
}

push_this_git() {
    echo "*** pushing $1 to $REMOTE_NAME:$REMOTE_DIR/$1"
    ssh $REMOTE_NAME bash -c "\"mkdir -p $REMOTE_DIR/$1; cd $REMOTE_DIR/$1; git init\""
    (cd $1; git push -f $REMOTE_NAME:$REMOTE_DIR/$1/.git HEAD:pending)
    ssh $REMOTE_NAME bash -c "\"cd $REMOTE_DIR/$1; git reset --hard pending\""
}

push_all_git() {
    for gd in $(find layers -maxdepth 3 -name .git -type d); do
        d=$(dirname $gd)
        push_this_git $d
    done
}

do_build() {
    cd $(dirname $0)/..
    case $1 in
    *.yml)
        ~/.local/bin/kas build --update $1
        ;;
    *.sh)
        ./$1
    esac
}

do_checkout() {
    cd $(dirname $0)/..
    case $1 in
    *.yml)
        echo "*** do checkout $1"
        ~/.local/bin/kas checkout --force-checkout --update $1
        ;;
    esac
}

echo "running on $(hostname) with args=$@"
if [ "$1" == on-remote ]; then
    shift
    do_build "$@"
elif [ "$1" == checkout ]; then
    shift
    do_checkout "$@"
else
    case $1 in
    ci/*|for-ref/*)
        TMP=${1#ci/}
        TMP=${1#for-ref/}
        TMP=${TMP%.yml}
        TMP=${TMP%.sh}
        BUILD_CONFIG=$TMP
    esac
    case $1 in
    *.yml)
        IS_YAML=true
        ;;
    *.sh)
        IS_YAML=false
        ;;
    *)
        echo "Expected either *.yml or *.sh and got $1"
        exit 2
        ;;
    esac
    local_config
    echo "Building on $REMOTE_NAME"
    push_this_git .
    if $IS_YAML & false; then
        ssh -t $REMOTE_NAME $REMOTE_DIR/scripts/remote-build checkout "$@"
        push_all_git
    fi
    ssh -t $REMOTE_NAME $REMOTE_DIR/scripts/remote-build on-remote "$@"
fi
